package OC240;
use strict;
use warnings;

our %description =
( debit => [ [ record_type => a2 => q{Code enregistrement} ]
    ,  [ record_id => a6 => q{Numéro de l’enregistrement} ]
    ,  [ operation => a2 => q{Code opération} ]
    ,  [ date => a6 => q{Date de règlement} ]
    ,  [ currency => a1 => q{Code monnaie} ]
    ,  [ garbage => a4 => q{Inutilisé} ]
    ,  [ issuer_bank => a5 => q{Code établissement émetteur} ]
    ,  [ issuer_branch => a5 => q{Code guichet émetteur} ]
    ,  [ issuer_account => a11 => q{Numéro de compte émetteur} ]
    ,  [ payer => a24 => q{Nom du donneur d’ordre} ]
    ,  [ issuer_country => a6 => q{Numéro National d’Emetteur} ]
    ,  [ bnf_reserved => a5 => q{Réservé BDF} ]
    ,  [ recipient_bank => a5 => q{Code établissement destinataire} ]
    ,  [ recipient_branch => a5 => q{Code guichet destinataire} ]
    ,  [ recipient_account => a11 => q{Numéro de compte destinataire} ]
    ,  [ recipient_name => a24 => q{Nom du destinataire} ]
    ,  [ bnf_reserved => a6 => q{Réservé BDF} ]
    ,  [ label_site => a24 => q{Libellé abréviatif de domiciliation} ]
    ,  [ label1 => a32 => q{Libellé 1} ]
    ,  [ label2 => a32 => q{Libellé 2} ]
    ,  [ garbage => a10 => q{Inutilisé} ]
    ,  [ flow => a2 => q{Code flux} ]
    ,  [ amount => a12 => q{Montant} ]]
, credit => [ [ record_type => a2 => q{Code enregistrement} ]
    ,  [ record_id => a6 => q{Numéro de l’enregistrement} ]
    ,  [ operation => a2 => q{Code opération} ]
    ,  [ date => a6 => q{Date de règlement} ]
    ,  [ currency => a1 => q{Code monnaie} ]
    ,  [ garbage => a4 => q{Inutilisé} ]
    ,  [ issuer_bank => a5 => q{Code établissement émetteur} ]
    ,  [ issuer_branch => a5 => q{Code guichet émetteur} ]
    ,  [ issuer_account => a11 => q{Numéro de compte émetteur} ]
    ,  [ payer => a24 => q{Nom du donneur d’ordre} ]
    ,  [ garbage => a6 => q{Inutilisé} ]
    ,  [ bnf_reserved => a5 => q{Réservé BDF} ]
    ,  [ recipient_bank => a5 => q{Code établissement destinataire} ]
    ,  [ recipient_branch => a5 => q{Code guichet destinataire} ]
    ,  [ recipient_account => a11 => q{Numéro de compte destinataire} ]
    ,  [ recipient_name => a24 => q{Nom du destinataire} ]
    ,  [ bnf_reserved => a6 => q{Réservé BDF} ]
    ,  [ label_site => a24 => q{Libellé abréviatif de domiciliation} ]
    ,  [ label1 => a32 => q{Libellé 1} ]
    ,  [ label2 => a32 => q{Libellé 2} ]
    ,  [ garbage => a10 => q{Inutilisé} ]
    ,  [ flow => a2 => q{Code flux} ]
    ,  [ amount => a12 => q{Montant} ]]
, total => [ [ record_type => a2 => q{Code enregistrement} ]
    ,  [ record_id => a6 => q{Numéro de l’enregistrement} ]
    ,  [ operation => a2 => q{Code opération} ]
    ,  [ date => a6 => q{Date de règlement} ]
    ,  [ currency => a1 => q{Code monnaie} ]
    ,  [ garbage => a4 => q{Inutilisé} ]
    ,  [ issuer_bank => a5 => q{Code établissement émetteur} ]
    ,  [ issuer_branch => a5 => q{Code guichet émetteur} ]
    ,  [ issuer_account => a11 => q{Numéro de compte émetteur} ]
    ,  [ payer => a24 => q{Nom du donneur d’ordre} ]
    ,  [ garbage => a6 => q{Inutilisé} ]
    ,  [ garbage => a156 => q{Inutilisé} ]
    ,  [ amount => a12 => q{Montant} ]]
, emiter => [ [ record_type => a2 => q{Code enregistrement} ]
    ,  [ record_id => a6 => q{Numéro de l’enregistrement} ]
    ,  [ garbage => a2 => q{Inutilisé} ]
    ,  [ date => a6 => q{Date d’échange} ]
    ,  [ currency => a1 => q{Code monnaie} ]
    ,  [ garbage => a4 => q{Inutilisé} ]
    ,  [ issuer_bank => a5 => q{Code établissement émetteur} ]
    ,  [ issuer_branch => a5 => q{Code guichet émetteur} ]
    ,  [ issuer_account => a11 => q{Numéro de compte émetteur} ]
    ,  [ payer => a24 => q{Nom du donneur d’ordre} ]
    ,  [ garbage => a6 => q{Inutilisé} ]
    ,  [ garbage => a168 => q{Inutilisé} ]]);

1;
